### ISSUE TITLE
Determine which files/directories are "valuable" and which aren't

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-river#1]
My first attempt at creating a package ends up with the following directory hierarchy:
```
usr/share/river/
usr/share/river/config.json
usr/share/river/docs/
usr/share/river/LICENSE
usr/share/river/lists/
usr/share/river/misc/
usr/share/river/node_modules/
usr/share/river/package.json
usr/share/river/package-lock.json
usr/share/river/README.md
usr/share/river/river5.js
usr/share/river/misc/dashboard.html
usr/share/river/misc/serverhomepage.html
usr/share/river/misc/template.html
usr/share/river/lists/hn.opml
usr/share/river/lists/myJsonFeeds.json
usr/share/river/lists/myOpmlFeeds.opml
usr/share/river/lists/myTxtFeeds.txt
usr/share/river/lists/nyt.opml
usr/share/river/docs/CONFIG.md
usr/share/river/docs/DROPBOXSUBSCRIPTIONLISTS.md
usr/share/river/docs/ELECTRIC.md
usr/share/river/docs/FORPOETS.md
usr/share/river/docs/HELLOWORLD.md
usr/share/river/docs/RIVEROFNEWS.md
usr/share/river/docs/ROADTORIVER5.md
usr/share/river/docs/UPGRADE.md
usr/lib/systemd/
usr/lib/systemd/system/
usr/lib/systemd/system/river@.service
var/
var/lib/
var/lib/river/
```
Where `node_modules/` contains lots of subdirectories.

Question for @scripting: which of the top-level directories under `usr/share/river` contain valueable user data, and which never do? I need this to "mark them up" with some metadata in the to-be-written UBOS manifest, so their content is backed up and restored when doing backups/restores and for server migration.

**Comment by scripting** [comment]
Johannes, it's going to take a bit for me to get around to this. 

I have no visualization of what's showing up at the other end.

River5 is designed so when you run it the first time it does something. 

I'm working in a completely different part of my codebase now, and cant switch gears that quickly. I'll make bad decisions if I do. 

Remember this shit has been ongoing for 18 years. ;-)

I have to have time to think. And that takes time. ;-)

**Comment by jernst** [comment]
Perfectly fine. No hurry needed :-) It's a little hard to visualize what's going on at the other end, this is in fact the biggest challenge for packaging apps for UBOS, as the "pipeline" has more steps that one would ordinarily expect:

source code (e.g. somewhere on Github) + build scripts (e.g. somewhere else on Github) => on build machine, create archive with `makepkg` => upload package to software depot => on target machine, download and install package => on target machine, install and configure app through with `ubos-admin createsite` or `ubos-admin deploy`.

But don't worry about that, River5 is nicely self-contained and easy to install, so this will be easier than it looks like.

**Comment by scripting** [comment]
Good. No hurry means we can do good work. ;-)

One more thing -- if we have the discussion in the other place people from
my blog can participate (they'll see notifications), a few of them run
River5 so might be able to fill in for me. A way to spread the load.

Dave

**Comment by jernst** [comment]
So the answer on these question seems to be:
* `data` is throwaway "cache" data
* `lists` is valuable, it's the feeds the user provided
* `rivers` is potentially valuable: generated from the feeds, but can be regenerated
